TXT_MAIN_NAME = "SSH (&) User Key Management"
TXT_MENU="Menu"
TXT_INCLUDED = "included"
TXT_NOT_INCLUDED = "not included"

TXT_TITLE_01 = "System users"
TXT_TITLE_02 = "Number of users"
TXT_TITLE_03 = "Select user"
TXT_TITLE_04 = "Create system user"
TXT_TITLE_055 = "Key list"
TXT_TITLE_05 = "Select user action"
TXT_TITLE_06 = "Select key action"

TXT_MENU_00 = "no sudo"
TXT_MENU_01 = "sudo access"
TXT_MENU_02 = "key count"

TXT_MENU2_TITLE_01 = "Edit user"
TXT_MENU2_TITLE_02 = "Number of keys"
TXT_MENU2_TITLE_03 = "Create new key"
TXT_MENU2_TITLE_04 = "Delete selected key"
TXT_MENU2_TITLE_05 = "Include key in authorized_keys"
TXT_MENU2_TITLE_06 = "Remove key from authorized_keys"
TXT_MENU2_TITLE_07 = "Show private key"
TXT_MENU2_TITLE_08 = "Delete system user and remove all data"
TXT_MENU2_TITLE_09 = "Change user password"
TXT_MENU2_TITLE_10 = "Update user SSH directory structure"
TXT_MENU2_TITLE_11 = "User SSH directory updated (for manager)"

TXT_MENU2_TITLE_12 = "Remove sudo permissions from user"
TXT_MENU2_TITLE_13 = "Add sudo permissions to user"
TXT_MENU2_TITLE_14 = "Updating user SSH directory structure"
TXT_MENU2_TITLE_15 = "Sudo permissions removed"
TXT_MENU2_TITLE_16 = "Removing sudo permissions from user"
TXT_MENU2_TITLE_17 = "Adding sudo permissions to user"
TXT_MENU2_TITLE_18 = "Sudo permissions added"

TXT_MENU2_TITLE_19 = "Remove user from dialout group (tty)"
TXT_MENU2_TITLE_20 = "Removing user from dialout group (tty)"
TXT_MENU2_TITLE_21 = "User removed from dialout group (tty)"
TXT_MENU2_TITLE_22 = "Add user to dialout group (tty)"
TXT_MENU2_TITLE_23 = "Adding user to dialout group (tty)"
TXT_MENU2_TITLE_24 = "User added to dialout group (tty)"
TXT_MENU2_TITLE_25 = "Error adding user to dialout group (tty)"
TXT_MENU2_TITLE_26 = "Error removing user from dialout group (tty)"
TXT_MENU2_TITLE_27 = "Dialout is the primary group of user {user}. Changing primary group to 'users'."

TXT_MENU3_TITLE_01 = "Edit selected user key"
TXT_MENU3_TITLE_02 = "Key"

TXT_MENU2_TITLE_28 = "Disable sudo without password for user"
TXT_MENU2_TITLE_29 = "Enable sudo without password for user"
TXT_MENU2_TITLE_29_not_available = "Enable sudo without password for user (not available, user is not a sudoer)"
TXT_MENU2_TITLE_30 = "Enable SSH password login for user"
TXT_MENU2_TITLE_31 = "Disable SSH password login for user"
TXT_MENU2_TITLE_31_not_available = "Disable SSH password login for user (not available, user has no keys)"

TXT_MENU2_TITLE_32 = "Enable sudo with password for user"
TXT_MENU2_TITLE_33 = "Now switching to sudo with password will be required for user"
TXT_MENU2_TITLE_34 = "Enable sudo without password for user"
TXT_MENU2_TITLE_35 = "Now switching to sudo without password will not be required for user"

TXT_MENU2_TITLE_36 = "Disable SSH password login for user"
TXT_MENU2_TITLE_37 = "Now SSH password login is disabled for user"
TXT_MENU2_TITLE_38 = "Enable SSH password login for user"
TXT_MENU2_TITLE_39 = "Now SSH password login is enabled for user"