TXT_MAIN_NAME = "SSH User Key Management"
TXT_MENU="Menu"
TXT_INCLUDED = "included"
TXT_NOT_INCLUDED = "not included"

TXT_TITLE_01 = "System users"
TXT_TITLE_02 = "Number of users"
TXT_TITLE_03 = "Select user"
TXT_TITLE_04 = "Create system user"
TXT_TITLE_05 = "Select user action"
TXT_TITLE_06 = "Select key action"

TXT_MENU_00 = "no sudo"
TXT_MENU_01 = "sudo access"
TXT_MENU_02 = "key count"

TXT_MENU2_TITLE_01 = "Edit user"
TXT_MENU2_TITLE_02 = "Number of keys"
TXT_MENU2_TITLE_03 = "Create new key"
TXT_MENU2_TITLE_04 = "Delete selected key"
TXT_MENU2_TITLE_05 = "Include key in authorized_keys"
TXT_MENU2_TITLE_06 = "Remove key from authorized_keys"
TXT_MENU2_TITLE_07 = "Show private key"
TXT_MENU2_TITLE_08 = "Delete system user and remove all data"
TXT_MENU2_TITLE_09 = "Change user password"
TXT_MENU2_TITLE_10 = "Update user SSH directory structure"
TXT_MENU2_TITLE_11 = "User SSH directory updated (for manager)"

TXT_MENU2_TITLE_12 = "Remove sudo permissions from user"
TXT_MENU2_TITLE_13 = "Add sudo permissions to user"
TXT_MENU2_TITLE_14 = "Updating user SSH directory structure"
TXT_MENU2_TITLE_15 = "Sudo permissions removed"
TXT_MENU2_TITLE_16 = "Removing sudo permissions from user"
TXT_MENU2_TITLE_17 = "Adding sudo permissions to user"
TXT_MENU2_TITLE_18 = "Sudo permissions added"

TXT_MENU3_TITLE_01 = "Edit selected user key"
TXT_MENU3_TITLE_02 = "Key"

