TX_OK               = "OK"
TX_FND              = "Nalezeno"
TX_DEF              = "Výchozí"
TX_ABORT            = "Ukončeno uživatelem."
TX_ERROR            = "CHYBA"
TX_BKG_START        = "Spouštím proces zálohování pro"
TX_BKG_ERR0         = "Chyba při vytváření zálohy pro"
TX_BKG_ERR1         = "Nebyly nalezeny platné domácí složky"
TX_BKG_ERR2         = "Chyba při vytváření 7z zálohy"
TX_BKG_ERR3         = "Nebyl nalezen žádný uživatel pro zálohování."
TX_BKG_ERR4         = "Chyba při vytváření kompletní 7z zálohy"
TX_BKG_ERR5         = "Uživatel neexistuje."
TX_BKG_ERR5_TX      = "Uživatel neexistuje {name}"
TX_BKG_ERR6         = "Domácí složka uživatele neexistuje."
TX_BKG_USER_INCL    = "uživatel(é) k zahrnutí do kompletní 7z zálohy."

TX_CFG_INI_ERR1     = "Chyba: Systémový uživatel {name} neexistuje."
TX_CFG_INI_ERR2     = "Chyba: Konfigurační soubor {pth} neexistuje."
TX_CFG_INI_ERR3     = "Chyba: Konfigurační soubor {pth} není platný."

TX_CFG_SAVED        = "Konfigurační soubor {pth} byl aktualizován."
TX_CFG_SV_RST       = "Restartování služby systemd..."
TX_CFG_SV_DONE      = "Konfigurace byla uložena."

TX_CFG_RST_ST       = "Zastavení služby systemd..."
TX_CFG_RST_STS      = "Spuštění služby systemd..."
TX_CFG_RST_OK       = "Služba systemd byla restartována."
TX_CFG_RST_ERR1     = "Chyba: Nepodařilo se restartovat službu systemd {name} při zastavení."
TX_CFG_RST_ERR2     = "Chyba: Nepodařilo se restartovat službu systemd {name} při spuštění."

TX_INST_HD1         ="Vytvoření nové instance Node-Red"
TX_INST_HD2         ="Systémový uživatel       "
TX_INST_HD3         ="Heslo                    "
TX_INST_HD4         ="Port                     "
TX_INST_HD5         ="Titulek stránky          "
TX_INST_HD6         ="Typ instalace            "

TX_INST_INP01       ="TITULEK (pro administraci a uživatelské stránky)"
TX_INST_INP02       ="ponechte prázdné pro použití uživatelského jména"
TX_INST_INP03       ="Systémového uživatele"

TX_INST_Q1          ="Potvrďte nastavení nové instance Node-Red"

TX_INST_ERR00       ="Chyba: Výchozí archiv Node-Red {pth} neexistuje."
TX_INST_ERR01       ="Uživatel {username} již existuje. Ukončuji."
TX_INST_ERR02       ="Chyba při vytváření nové instance Node-Red: {e}"

TX_INST_MAKE_ERR01  ="Chyba: Neplatné uživatelské jméno."
TX_INST_MAKE_ERR02  ="Chyba: Uživatel, Domácí složka nebo Instance již existuje."
TX_INST_MAKE_ERR03  ="Chyba při vytváření systémového uživatele {username}: {e}"
TX_INST_MAKE_ERR04  ="Chyba: Domácí složka uživatele neexistuje."
TX_INST_MAKE_ERR05  ="Chyba: Složka {asset} neexistuje."
TX_INST_MAKE_ERR06  ="Chyba: Výchozí archiv Node-Red {pth} neexistuje."
TX_INST_MAKE_ERR07  ="Chyba při extrahování výchozího nastavení Node-Red: {e}"
TX_INST_MAKE_ERR08  ="Chyba při čtení {name}: {e}"
TX_INST_MAKE_ERR09  ="Chyba při zápisu {name}: {e}"
TX_INST_MAKE_ERR10  ="Chyba: Služba pro"
TX_INST_MAKE_ERR10_1 ="neexistuje"
TX_INST_MAKE_ERR10_2 ="nelze povolit"
TX_INST_MAKE_ERR10_3 ="nelze spustit"
TX_INST_MAKE_ERR11  ="Chyba: Soubor šablony služby neexistuje. Nelze vytvořit instanci, protože ji nelze spustit."

TX_INST_MAKE01      ="Extrahování výchozího nastavení Node-Red do {pth}..."
TX_INST_MAKE02      ="Výchozí nastavení Node-Red bylo extrahováno do {pth}."
TX_INST_MAKE03      ="Přesouvání výchozího nastavení Node-Red do {pth}..."
TX_INST_MAKE04      ="Čištění dočasného adresáře..."
TX_INST_MAKE05      ="Nastavení vlastnictví domácí složky..."
TX_INST_MAKE06      ="Aktualizace skriptů v domácí složce uživatele..."
TX_INST_MAKE07      ="Získání instance služby..."
TX_INST_MAKE08      ="Vytváření symlink systemd, povolení a spuštění služby..."
TX_INST_MAKE09      ="Služba povolena, spouštění..."
TX_INST_MAKE_OK     ="OK: Instance Node-Red pro {name} byla úspěšně nastavena."
TX_INST_MAKE_STR    ="Vytváření adresářové struktury pro {name}..."
TX_INST_MAKE_INST   ="Instalace aktuální čisté verze Node-RED z repozitáře..."

TX_REM_ERR1         ="Tento uživatel nemá nastavenou instanci Node-Red."
TX_REM_ERR2         ="Uživatelská jména nesouhlasí. Ukončuji."
TX_REM_ERR3         ="Chyba: Služba není inicializována pro uživatele."
TX_REM_ERR4         ="Chyba: Služba neexistuje - domácí složka pro '{name}' není instancí Node-Red."
TX_REM_ERR5         ="Chyba: Službu se nepodařilo zastavit."
TX_REM_ERR6         ="Chyba: Službu se nepodařilo zakázat."

TX_REM_TXT0         ="Zastavení služby..."
TX_REM_TXT1         ="Zakázání služby..."
TX_REM_TXT2         ="Služba byla zastavena a zakázána."
TX_REM_TXT_OK       ="OK: Instance Node-Red pro {name} byla úspěšně odstraněna."

TX_BKG_ERR7         ="Chyba při vytváření nebo získání zálohovací složky"

TX_BKG_TXT00        ="Vytváření kompletní 7z zálohy pro {num} uživatelů..."
TX_BKG_TXT00_1      ="Vytváření 7z zálohy pro systémového uživatele: {name}"
TX_BKG_TXT01        ="Do adresáře: {pth}"
TX_BKG_TXT02        ="Název souboru: {name}"

TX_FRESH_ERR0       ="Instance již existuje na {path}"
TX_FRESH_ERR1       ="Instalace selhala s chybou: {e}"
TX_FRESH_ERR2       ="Neočekávaná chyba: {e}"

TX_INST_TYPE_0      ="čistá instalace z repozitáře"
TX_INST_TYPE_1      ="z archivu"
TX_INST_TYPE_None   ="nenastaveno"

TX_INST_TYPE_Q = (
    "Vyberte typ instalace:\n"
    "ESC instalaci zruší."
)
TX_INST_TYPE_INP    ="Typ instalace: "
TX_INST_TYPE_INP_o1 ="Instalace z repozitáře - nejnovější verze"
TX_INST_TYPE_INP_o2 ="Instalace z archivu"


TXT_MENU_INSTN_del_inst0 = "Opravdu smazat systémového uživatele?"
TXT_MENU_INSTN_del_inst1 = "Systémový uživatel bude smazán spolu s jeho domácím adresářem, který bude nejprve zálohován. Jste si jistý, že chcete pokračovat?\nOpravdu víte, co děláte?\nStiskněte N pro zahájení zálohy a smazání."

TX_NODEJS_APT_CHECK_ERR = "Chyba při ověření NodeSource APT instalace: %s"
TX_NODEJS_READ_FILE_ERR = "Chyba při čtení %s: %s"
TX_NODEJS_TARGET_MAJOR_ERR = "Nepodařilo se určit cílovou verzi Node.js."
TX_NODEJS_UPDATE_RUN = "Provádím update Node.js z verze %s na %s."
TX_NODEJS_REPO_CONFIGURE_RUN = "Nastavuji NodeSource repozitář pro Node.js verze %s."
TX_NODEJS_REPO_CONFIGURED = "NodeSource repozitář pro Node.js verze %s byl nastaven."
TX_NODEJS_REPO_CONFIGURE_SKIP = "NodeSource repozitář už je nastaven pro Node.js verze %s. Přenastavení se přeskočí."
TX_NODEJS_PURGE_RUN = "Odebírám aktuálně nainstalovaný Node.js před přechodem z major verze %s na %s."
TX_NODEJS_PURGE_DONE = "Předchozí balík Node.js pro major verzi %s byl odebrán."
TX_NODEJS_INSTALL_RUN = "Provádím instalaci Node.js ve verzi %s."
TX_NODEJS_PACKAGE_UPGRADE_RUN = "Aktualizuji nainstalovaný balík Node.js v rámci major verze %s."
TX_NODEJS_INSTALL_UPDATE_SUCCESS = "Instalace/update Node.js verze %s byla dokončena."
TX_NODEJS_NEW_VERSION_ERR = "Instalace/update proběhl, ale nepodařilo se zjistit novou verzi Node.js."
TX_NODEJS_NOT_GLOBAL_AFTER = "Po instalaci/update Node.js nevypadá jako globální instalace."
TX_NODEJS_AFTER_EXPECTED_MIN = "Po instalaci/update je verze {new_major}, očekávána byla alespoň {target_major}."
TX_NODEJS_AFTER_EXPECTED_EXACT = "Po instalaci/update je verze {new_major}, očekávána byla {target_major}."
TX_NODEJS_AVAILABLE_MAJOR = "Node.js je nyní dostupný v major verzi %s."
TX_NODEJS_UPDATED_OK = "Node.js byl úspěšně aktualizován na verzi {new_major}. Předchozí verze byla {current_major}."
TX_NODEJS_INSTALLED_OK = "Node.js byl úspěšně globálně nainstalován ve verzi {new_major}."
TX_NODEJS_INSTALL_UPDATE_ERR = "Chyba při instalaci/update Node.js: %s"
TX_NODEJS_INSTALL_UPDATE_FAILED = "Instalace/update Node.js selhal: {msg}"
TX_NODEJS_INSTALL_UPDATE_SYS_ERR = "Systémová chyba při instalaci/update Node.js: %s"
TX_NODEJS_INSTALL_UPDATE_SYS_FAILED = "Systémová chyba při instalaci/update Node.js: {err}"
TX_NODEJS_INSTALL_ROOT_ERR = "Instalace Node.js musí být spuštěna jako root."
TX_NODEJS_ALREADY_INSTALLED = "Node.js je již globálně nainstalován ve verzi {current_major}."
TX_NODEJS_REMOVE_ROOT_ERR = "Odstranění Node.js musí být spuštěno jako root."
TX_NODEJS_REMOVE_NOT_INSTALLED = "Globální Node.js momentálně není nainstalovaný."
TX_NODEJS_REMOVE_RUN = "Odstraňuji globální balík Node.js verze %s."
TX_NODEJS_REMOVE_DONE = "Globální balík Node.js verze %s byl odstraněn."
TX_NODEJS_PURGE_ONLY_RUN = "Provádím purge globálního balíku Node.js verze %s."
TX_NODEJS_PURGE_ONLY_DONE = "Globální balík Node.js verze %s byl purge odstraněn."
TX_NODEJS_REMOVED_OK = "Globální Node.js verze {ver} byla úspěšně odstraněna."
TX_NODEJS_PURGED_OK = "Globální Node.js verze {ver} byla úspěšně purge odstraněna."
TX_NODEJS_REMOVE_STILL_PRESENT = "Node.js po odstranění stále vypadá jako globálně nainstalovaný. Detekovaná verze: {ver}."
TX_NODEJS_REMOVE_ERR = "Odstranění Node.js selhalo: %s"
TX_NODEJS_REMOVE_FAILED = "Odstranění Node.js selhalo: {msg}"
TX_NODEJS_REMOVE_SYS_ERR = "Systémová chyba při odstraňování Node.js: %s"
TX_NODEJS_REMOVE_SYS_FAILED = "Systémová chyba při odstraňování Node.js: {err}"
TX_NODEJS_UPDATE_ROOT_ERR = "Update Node.js musí být spuštěn jako root."
TX_NODEJS_CURRENT_VERSION_ERR = "Nepodařilo se zjistit aktuální verzi Node.js."
TX_NODEJS_NOT_GLOBAL = "Node.js není globální systémová instalace."
TX_NODEJS_NOT_NODESOURCE = "Node.js není detekován jako APT instalace z NodeSource."
TX_NODEJS_ALREADY_LTS = "Node.js je již na verzi {current_major}, což je >= poslední nastavené LTS {target_major}."
TX_NODEJS_ALREADY_TARGET = "Node.js je již na požadované verzi {current_major}."
TX_NODEJS_UPDATE_REPO_RUN = "Provádím update Node.js z verze %s na %s (NodeSource repo bylo %s)."
