TX_OK               = "OK"
TX_FND              = "Found"
TX_DEF              = "Default"
TX_ABORT            = "Aborted by user."
TX_ERROR            = "ERROR"
TX_OFF              = "OFF"
TX_BKG_START        = "Starting backup process for"
TX_BKG_ERR0         = "Error creating backup for"
TX_BKG_ERR1         = "No valid home directories found"
TX_BKG_ERR2         = "Error creating 7z backup"
TX_BKG_ERR3         = "No users found for backup."
TX_BKG_ERR4         = "Error creating full 7z backup"
TX_BKG_ERR5         = "User does not exist."
TX_BKG_ERR5_TX      = "User does not exist {name}"
TX_BKG_ERR6         = "User home directory does not exist."
TX_BKG_USER_INCL    = "user(s) to include in full 7z backup."
TX_BKG_ERR6_TX      = "Error updating settings.js for user {name}"
TX_BKG_ERR7         = "Error creating or getting backup directory"
TX_BKG_ERR8         = "Error reading backup directory"
TX_BKG_ERR9         = "Backup file does not exist"
TX_BKG_ERR10        = "Backup file could not be deleted - error"

TX_BKG_ERR11        = "Integrity error detected: {err}"
TX_BKG_ERR12        = "Error: 7z utility is not installed"
TX_BKG_INT_OK       = "Backup integrity is fine"
TX_BKG_7Z_NOT_FOUND = "Error: 7z utility is not installed."
TX_BKG_INT_IRR      = "Integrity error: {e}"

TX_NO_DIR           = "Directory does not exist."
TX_NO_BACKUPS       = "No backups found."

TX_BKG_DEL_Q        = "Really delete backup {fileName} ?"

TX_BKG_FND          = "Found backups:"
TX_BKG_USER_SEL     = "Select backup:"

TX_HD_VERSION       = "Config version"
TX_HD_URL           = "Server URL"
TX_HD_BKG_DIR       = "Backup directory"
TX_HD_USER          = "System user"
TX_HD_NODE_USER     = "Node user"
TX_HD_SERV_VER      = "Service file version"
TX_HD_InstanceTitle = "Page title"
TX_HD_SSL_STATUS    = "SSL status"
TX_HD_SSL_CFG       = "config (Verified) enabled"
TX_HD_SSL_SELF      = "Self-signed enabled"
TX_HD_SSL_NAN       = "not set"
TX_HD_USR_NF        = "not found"
TX_HD_USR_TERR      = "type error"

TX_CFG_INI_ERR1     = "Error: System user {name} does not exist."
TX_CFG_INI_ERR2     = "Error: Configuration file {pth} does not exist."
TX_CFG_INI_ERR3     = "Error: Configuration file {pth} is not valid."

TX_CFG_SAVED        = "Configuration file {pth} has been updated."
TX_CFG_SV_RST       = "Restarting systemd service..."
TX_CFG_SV_DONE      = "Configuration has been saved."

TX_CFG_RST_ST       = "Stopping systemd service..."
TX_CFG_RST_STS      = "Starting systemd service..."
TX_CFG_RST_OK       = "Systemd service has been restarted."
TX_CFG_RST_ERR1     = "Error: Failed to restart systemd service {name} at stop."
TX_CFG_RST_ERR2     = "Error: Failed to restart systemd service {name} at start."

TX_INST_HD1         ="Creating new node instance"
TX_INST_HD2         ="System user          "
TX_INST_HD3         ="Password             "
TX_INST_HD4         ="Port                 "
TX_INST_HD5         ="Page Title           "
TX_INST_HD6         ="Type of installation "

TX_INST_INP01       ="TITLE (for admin and UI pages)"
TX_INST_INP02       ="leave empty to use the username"
TX_INST_INP03       ="For system user"

TX_INST_Q1          ="Confirm the new node instance setup"

TX_INST_ERR00       ="Error: Default node archive {pth} does not exist."
TX_INST_ERR01       ="User {username} already exists. Aborting."
TX_INST_ERR02       ="Error creating new node instance: {e}"

TX_INST_MAKE_ERR01  ="Error: Invalid username."
TX_INST_MAKE_ERR02  ="Error: User, UserHome or Instance already exists."
TX_INST_MAKE_ERR03  ="Error creating system user {username}: {e}"
TX_INST_MAKE_ERR04  ="Error: User home directory does not exist."
TX_INST_MAKE_ERR05  ="Error: Asset {asset} does not exist."
TX_INST_MAKE_ERR06  ="Error: Node archive {pth} does not exist."
TX_INST_MAKE_ERR07  ="Error extracting default node setup: {e}"
TX_INST_MAKE_ERR08  ="Error reading {name}: {e}"
TX_INST_MAKE_ERR09  ="Error writing {name}: {e}"
TX_INST_MAKE_ERR10  ="Error: Service for"
TX_INST_MAKE_ERR10_1 ="does not exist"
TX_INST_MAKE_ERR10_2 ="could not be enabled"
TX_INST_MAKE_ERR10_3 ="could not be started"
TX_INST_MAKE_ERR11  ="Error: Service template file does not exist. Cannot create instance because it cannot be started."

TX_INST_MAKE01      ="Extracting default node setup to {pth}..."
TX_INST_MAKE02      ="Default node setup extracted to {pth}."
TX_INST_MAKE03      ="Moving default node setup to {pth}..."
TX_INST_MAKE04      ="Cleaning up temporary directory..."
TX_INST_MAKE05      ="Setting ownership of home directory..."
TX_INST_MAKE06      ="Updating scripts in user's home directory..."
TX_INST_MAKE07      ="Get service instance..."
TX_INST_MAKE08      ="Creating systemd link, enabling and starting service..."
TX_INST_MAKE09      ="Service enabled, starting..."
TX_INST_MAKE_OK     ="OK:Node instance for {name} has been successfully set up."
TX_INST_MAKE_STR    ="Creating directory structure for {name}..."
TX_INST_MAKE_INST   ="Installing current clean version of Node-RED from the repository..." 

TX_REM_ERR1         ="This user does not have a Node instance set up."
TX_REM_ERR2         ="Usernames do not match. Aborting"
TX_REM_ERR3         ="Error: Service not initialized for user."
TX_REM_ERR4         ="Error: Service does not exist - home user for '{name}' is not a Node instance."
TX_REM_ERR5         ="Error: Service could not be stopped."
TX_REM_ERR6         ="Error: Service could not be disabled."

TX_REM_TXT0         ="Stopping service..."
TX_REM_TXT1         ="Disabling service..."
TX_REM_TXT2         ="Service has been stopped and disabled."
TX_REM_TXT22        ="Service has been stopped."
TX_REM_TXT_OK       ="OK:Node instance for {name} has been successfully removed."

TX_BKG_TXT00        ="Creating full 7z backup for {num} users..."
TX_BKG_TXT00_1      ="Creating 7z backup for sys username: {name}"
TX_BKG_TXT01        ="To directory: {pth}"
TX_BKG_TXT02        ="Filename: {name}"

TX_FRESH_ERR0       ="Instance already exists at {path}"
TX_FRESH_ERR1       ="Installation failed with error: {e}"
TX_FRESH_ERR2       ="Unexpected error: {e}"

TX_INST_TYPE_0      ="fresh from repository"
TX_INST_TYPE_1      ="from archive"
TX_INST_TYPE_None   ="not set"

TX_INST_TYPE_Q = (
    "Choose installation type:\n"
    "ESC will cancel the installation."
)
TX_INST_TYPE_INP    ="Installation type: "
TX_INST_TYPE_INP_o1 ="Clean installation from the repository - latest version"
TX_INST_TYPE_INP_o2 ="Installation from an archive"

TXT_MENU_INSTN_del_inst0= "Really delete this system user ?"
TXT_MENU_INSTN_del_inst1= "The system user will be deleted along with their home directory, which will be backed up first. Are you sure you want to proceed?\nReally know what you're doing?\nPress N for begin backup and delete."
TX_REM_CANCEL    = "Deletion canceled."


TXT_MENU_INSTN_update_00= "Really update this node-red instance to the latest version ?"
TXT_MENU_INSTN_update_ok= "Node-red instance has been successfully updated for user {name}."

TX_UPD_RUNNING_UPD = "Updating Node-RED instance..."
TX_UPD_RUN_SRV = "Starting service ..."

TX_POST_INST_ERR01_TX = "Script cannot create log directory for user {name}."
TX_INST_MAKE_ERR12 = "Script cannot create directory structure"


TX_INST_MAKE_ZIPERR02 = "Invalid installation type: {tp}"

TX_INST_ERR03 = "!!! Port {port} is already in use, try another one. !!!"


TXT_BKG_MNG_RESTORE_Q1="Do you really want to restore the instance from a backup?"
TXT_BKG_MNG_RESTORE_Q2 = "Do you want to cancel the restoration and keep the current configuration?"
TXT_BKG_MNG_RESTORE_Q3="To confirm, please type the instance name: "
TXT_BKG_MNG_ERR12="The entered name does not match. Restore has been aborted."
TXT_BKG_MNG_ERR13="Restore failed: {err}"
TXT_BKG_MNG_ERR14="Unable to determine the root directory inside the archive."
TXT_BKG_MNG_ERR15="Failed to set permissions on restored files: {err}"
TXT_BKG_MNG_OK_RESTORED="The instance was successfully restored from backup."

TXT_BKG_MNG_STOPPING_SERVICE="Stopping Node-RED service..."
TXT_BKG_MNG_ERR_STOP="Failed to stop the Node-RED service. Restore aborted."
TXT_BKG_MNG_STARTING_SERVICE="Starting Node-RED service..."
TXT_BKG_MNG_ERR_START="Failed to start the Node-RED service after restore."
TXT_BKG_MNG_RESTORE_PREPARE = "Preparing to restore backup for user {usr}, file {fnm}"
TX_BKG_COPY_ADDFILE_OK = "Additional file {file} copied successfully."

TX_NODEJS_APT_CHECK_ERR = "Error verifying NodeSource APT installation: %s"
TX_NODEJS_READ_FILE_ERR = "Error reading %s: %s"
TX_NODEJS_TARGET_MAJOR_ERR = "Failed to determine target Node.js version."
TX_NODEJS_UPDATE_RUN = "Updating Node.js from version %s to %s."
TX_NODEJS_REPO_CONFIGURE_RUN = "Configuring the NodeSource repository for Node.js version %s."
TX_NODEJS_REPO_CONFIGURED = "The NodeSource repository for Node.js version %s has been configured."
TX_NODEJS_REPO_CONFIGURE_SKIP = "The NodeSource repository is already configured for Node.js version %s. Reconfiguration is skipped."
TX_NODEJS_PURGE_RUN = "Removing the currently installed Node.js package before switching from major version %s to %s."
TX_NODEJS_PURGE_DONE = "The previous Node.js package for major version %s has been removed."
TX_NODEJS_INSTALL_RUN = "Installing Node.js version %s."
TX_NODEJS_PACKAGE_UPGRADE_RUN = "Upgrading the installed Node.js package within major version %s."
TX_NODEJS_INSTALL_UPDATE_SUCCESS = "Installation/update of Node.js version %s completed."
TX_NODEJS_NEW_VERSION_ERR = "Installation/update completed, but failed to detect the new Node.js version."
TX_NODEJS_NOT_GLOBAL_AFTER = "After installation/update, Node.js no longer appears to be a global installation."
TX_NODEJS_AFTER_EXPECTED_MIN = "After installation/update, version is {new_major}; expected at least {target_major}."
TX_NODEJS_AFTER_EXPECTED_EXACT = "After installation/update, version is {new_major}; expected {target_major}."
TX_NODEJS_AVAILABLE_MAJOR = "Node.js is now available in major version %s."
TX_NODEJS_UPDATED_OK = "Node.js was successfully updated to version {new_major}. Previous version was {current_major}."
TX_NODEJS_INSTALLED_OK = "Node.js was successfully installed globally in version {new_major}."
TX_NODEJS_INSTALL_UPDATE_ERR = "Installation/update of Node.js failed: %s"
TX_NODEJS_INSTALL_UPDATE_FAILED = "Node.js installation/update failed: {msg}"
TX_NODEJS_INSTALL_UPDATE_SYS_ERR = "System error during Node.js installation/update: %s"
TX_NODEJS_INSTALL_UPDATE_SYS_FAILED = "System error during Node.js installation/update: {err}"
TX_NODEJS_INSTALL_ROOT_ERR = "Node.js installation must be run as root."
TX_NODEJS_ALREADY_INSTALLED = "Node.js is already installed globally in version {current_major}."
TX_NODEJS_REMOVE_ROOT_ERR = "Node.js removal must be run as root."
TX_NODEJS_REMOVE_NOT_INSTALLED = "Global Node.js is not currently installed."
TX_NODEJS_REMOVE_RUN = "Removing the global Node.js package version %s."
TX_NODEJS_REMOVE_DONE = "The global Node.js package version %s has been removed."
TX_NODEJS_PURGE_ONLY_RUN = "Purging the global Node.js package version %s."
TX_NODEJS_PURGE_ONLY_DONE = "The global Node.js package version %s has been purged."
TX_NODEJS_REMOVED_OK = "Global Node.js version {ver} was removed successfully."
TX_NODEJS_PURGED_OK = "Global Node.js version {ver} was purged successfully."
TX_NODEJS_REMOVE_STILL_PRESENT = "Node.js still appears to be installed globally after removal. Detected version: {ver}."
TX_NODEJS_REMOVE_ERR = "Node.js removal failed: %s"
TX_NODEJS_REMOVE_FAILED = "Node.js removal failed: {msg}"
TX_NODEJS_REMOVE_SYS_ERR = "System error during Node.js removal: %s"
TX_NODEJS_REMOVE_SYS_FAILED = "System error during Node.js removal: {err}"
TX_NODEJS_UPDATE_ROOT_ERR = "Node.js update must be run as root."
TX_NODEJS_CURRENT_VERSION_ERR = "Failed to determine the current Node.js version."
TX_NODEJS_NOT_GLOBAL = "Node.js is not a global system installation."
TX_NODEJS_NOT_NODESOURCE = "Node.js was not detected as a NodeSource APT installation."
TX_NODEJS_ALREADY_LTS = "Node.js is already on version {current_major}, which is >= the configured latest LTS {target_major}."
TX_NODEJS_ALREADY_TARGET = "Node.js is already on the requested version {current_major}."
TX_NODEJS_UPDATE_REPO_RUN = "Updating Node.js from version %s to %s (NodeSource repository was %s)."
TX_NODEJS_UPDATE_NPM_NO_INSTANCE = "The selected user does not have a Node-RED instance."
TX_NODEJS_UPDATE_NPM_NO_HOME = "Failed to determine the home directory for the selected user."
TX_NODEJS_UPDATE_NPM_NO_NPM = "The npm executable was not found in the system PATH."
TX_NODEJS_UPDATE_NPM_NO_INSTANCE_DIR = "The Node-RED instance directory does not exist."
TX_NODEJS_UPDATE_NPM_ERR = "npm update failed: %s"
TX_NODEJS_UPDATE_NPM_FAILED = "npm update failed: {msg}"
TX_NODEJS_UPDATE_NPM_SYS_ERR = "System error during npm update: %s"
TX_NODEJS_UPDATE_NPM_SYS_FAILED = "System error during npm update: {err}"
TX_NPM_UPDATE_RUN = "Running npm update for the global instance's Node.js installation..."
TX_NODEJS_UPDATE_NPM_QUESTION = "Do you also want to run 'npm update -g npm'\nto update the global npm package after updating Node.js?"
TX_NPM_UPDATE_SUCCESS = "Global npm package update completed successfully."