TXT_VER = "Version"
TXT_ERROR = "Error"
TXT_NODE = "NODE-RED"
TXT_ACC = "Access"
TXT_SAVE = "Save changes"
TXT_MENU = "Menu"
TXT_OPT = "Options"
TXT_TITLE_INSTANCE = "Instance"
TXT_TITLE_NDR_USR = "Node-Red Users"
TXT_PORT = "port"
TX_OFF = "OFF"

TXT_BKG_FOUND = "Found backups\n  Select a backup for further actions"
TXT_BKG_DELETED = "Backup file {fnm} for user {usr} has been deleted"
TXT_BKG_INV_SEL = "Invalid selection"
TXT_BKG_INT_OK = "Backup integrity is fine"

TXT_BKG_INT_CHECK = "Check backup integrity for file {fnm}"

TXT_MAIN_NAME = "Node-Red Service Manager"

TXT_MENU0_BKG_DIR = "Backup directory"
TXT_MENU0_TEMP = "Temp directory"
TXT_MENU0_DEFAULT_INSTANCE_FILENAME = "Instance info to dir"

TXT_MENU0_HOME = "MAIN MENU"
TXT_MENU0_INSTALL = "Install a new node instance"
TXT_MENU0_UPD_SUDO_FL = "Update sudoers file for node-red instances"
TXT_MENU0_UPD_SUDO_FL_HLP = "Show help for sudoers file configuration"
TXT_MENU0_EDIT = "New/edit instance"
TXT_MENU0_BACKUP = "Backup all node instances"
TXT_MENU0_BACKUP_LIST = "List backups"
TXT_MENU0_RLY_MK = "Really create full backup for all users"
TXT_MENU0_SERVICE = "!!! Service template missing !!! Create a service template"
TXT_MENU0_SERVICE_REM = "Remove-Uninstall service template"
TXT_MENU0_SERVICE_UPD = "Update service template"
TXT_MENU0_serv_removed = "Service template removed"
TXT_MENU0_serv_created = "Service template created"
TXT_MENU_rly_rem_tmpl = "Really remove service file?"
TXT_MENU0_RLY_UPD = "Really update service template?"
TXT_MENU0_inst_count_err ="There are still system user instances detected in user home directories.\nRemove them first. Found: {num}"
TXT_MENU0_SERV_VER = "Service file version"
TXT_UPDATE_SUDOERS_SURE_QUESTION = "Really update sudoers file for node-red instances?"
TXT_UPDATE_SUDOERS_FILE_ERROR = "Error updating sudoers file: {err}"
TXT_UPDATE_SUDOERS_FILE_OK = "Sudoers file updated successfully."
TXT_MENU_SUDOER_HELP_FILE = "sudoers_node_red_help.txt"

TXT_MENUSEL_TIT = "EDIT NODE INSTANCE"
TXT_MENUSEL_AFTERMN = "Select system user with node instance to edit"

TXT_MENU_INSTN_afterMenu=" Hint:\n  - 'Force Save' will also refresh the HTTPS settings\n "
TXT_MENU_INSTN_editNodeInst="Edit node instance"
TXT_MENU_INSTN_editNodeInst2="for selected system user "

TXT_MENU_INSTN_sysUser  = "System user:     "
TXT_MENU_INSTN_title    = "Title:           "
TXT_MENU_INSTN_url      = "URL:             "
TXT_MENU_INSTN_run      = "Service running: "
TXT_MENU_INSTN_port     = "Port:            "
TXT_MENU_INSTN_nd_us    = "Node User:       "
TXT_MENU_INSTN_nd_acl   = "Permissions:     "

TXT_MENU_INSTN_noInit   = "Service not initialized for user"
TXT_MENU_INSTN_u_edit   = "Users Edit"
TXT_MENU_INSTN_tit_ch   = "Change title"
TXT_MENU_INSTN_p_ch     = "Change port"
TXT_MENU_INSTN_bkg      = "Backup node instance"
TXT_MENU_INSTN_bkg_del  = "Manage backup files"
TXT_MENU_INSTN_bkg_del_c  = "Files: {cnt}"

TXT_MENU_INSTN_sts      = "Node service status"
TXT_MENU_INSTN_s_stop   = "Stop node service"
TXT_MENU_INSTN_s_res    = "Restart node service"
TXT_MENU_INSTN_s_res_q  = "Really restart service ?"
TXT_MENU_INSTN_s_start  = "Start node service"
TXT_MENU_INSTN_s_ena    = "Enable node service"
TXT_MENU_INSTN_s_dis    = "Disable node service"
TXT_MENU_INSTN_s_del    = "Delete node instance"
TXT_MENU_INSTN_s_upd    = "Update Node-Red instance"
TXT_MENU_INSTN_log      = "Show journalctl log - live"

TXT_MENU_INSTN_s_upd_lat = "Force update to the latest version of Node-RED"
TXT_MENU_INSTN_s_upd_latQ = "Really update to the latest version of Node-RED? This may include a major version upgrade."

TXT_MENU_INSTN_f_save   = "Force save config"
TXT_MENU_INSTN_ssl      = "Update https (save config and restart service)"
TXT_MENU_INSTN_del_inst_Err = "Error deleting node instance"
TXT_MENU_INSTN_ed_tit   = "title for admin and UI pages (leave empty for username)"
TXT_MENU_INSTN_ed_port_err = "Invalid port. Please enter a valid number."
TXT_MENU_INSTN_rly_bkg  = "Really backup node instance?"
TXT_MENU_INSTN_s_rs_1   = "Error: Failed to start systemd service."
TXT_MENU_INSTN_s_rs_2   = "Systemd service has been started."
TXT_MENU_INSTN_s_st_1   = "Error: Failed to stop systemd service."
TXT_MENU_INSTN_s_st_2   = "Systemd service has been stopped."
TXT_MENU_INSTN_s_dis_q  = "Really disable node service?"
TXT_MENU_INSTN_s_dis_1  = "Error: Failed to disable systemd service."
TXT_MENU_INSTN_s_dis_2  = "Systemd service has been disabled."
TXT_MENU_INSTN_s_ena_q  = "Really enable node service?"
TXT_MENU_INSTN_s_ena_1  = "Error: Failed to enable systemd service."
TXT_MENU_INSTN_s_ena_2  = "Systemd service has been enabled."
TXT_MENU_INSTN_save_q   = "Really save changes ?"
TXT_MENU_INSTN_save_ex_q  = "Save changes before exit ?"
TXT_MENU_INSTN_ssl_u    = "HTTPS updated from config"
TXT_MENU_INSTN_ssl_uSelf = "HTTPS updated from self-signed certificate"
TXT_MENU_INSTN_ssl_uEr  = "Error updating HTTPS"
TXT_MENU_INSTN_app_run  = "Run as application"
TXT_MENU_INSTN_app_run_safe  = "Run as application - SAFE MODE (flow stopped)"
TXT_MENU_INSTN_set_upd  = "Update settings.js file"

TXT_MENU_INSTN_U_noInit = "Service not initialized for user"
TXT_MENU_INSTN_U_add    = "Add new USer"
TXT_MENU_INSTN_U_sec    = "Secure Dashboard User"
TXT_MENU_INSTN_U_ns     = "UI user not set"
TXT_MENU_INSTN_U_ovw    = "Overwrite Dashboard User"
TXT_MENU_INSTN_U_rem    = "Remove Dashboard User"
TXT_MENU_INSTN_tit1     = "EDIT NODE INSTANCE"
TXT_MENU_INSTN_tit2     = "for selected system user"
TXT_MENU_INSTN_nd_i     = "add new node user"
TXT_MENU_INSTN_u_i      = "set UI user"
TXT_MENU_INSTN_u_rem_rly = "Really remove UI user ?"
TXT_MENU_INSTN_SC_INSTANCE = "INSTANCE"
TXT_MENU_INSTN_SC_SERVICE  = "SERVICE"
TXT_MENU_INSTN_SC_HTTPS = "HTTPS"
TXT_MENU_INSTN_SC_GEN   = "General"

TXT_MENU_CREATE_CRT     = "Create self-signed certificate - enable HTTPS"
TXT_MENU_CREATE_CRT_DIS = "Delete self-signed certificate - disable HTTPS"

TXT_Q_RLY_CREATE_CRT    = "Really create self-signed certificate ? Instance will be restarted."
TXT_Q_RLY_CREATE_CRT_DEL= "Really delete self-signed certificate ? Instance will be restarted."

TXT_MENU_NDUSR_ro       = "Change to readOnly access"
TXT_MENU_NDUSR_rw       = "Change to read-write access"
TXT_MENU_NDUSR_pwd      = "Change password"
TXT_MENU_NDUSR_del      = "Delete node user"
TXT_MENU_NDUSR_del_q    = "Really delete this node user ?"
TXT_MENU_NDUSR_del_err  = "Cannot delete the only user. Add new user first."

TX_MENU_NDU_TIT1        = "EDIT NODE USER"
TX_MENU_NDU_TIT2        = "for selected system user"

TX_Q_001                = "Really update node-red instance settings.js file ?"
TX_T_001                = "settings.js file updated"

TX_Q_002                = "Really create directories for instance {id} ?"
ERR_PI_001              = "Error creating directories for instance {id}, error: {e}"

TXT_MENU_PSINSR_REP     = "Repair instance directories like logs etc."
TXT_MENU_INSTN_show_help = "Show CFG help & info"
TXT_MENU_INSTN_cfg_help_Err = "Error reading help file"
TXT_MENU_INSTN_cfg_help_fileName = "setting_help.txt"

TXT_MENU_INSTN_MNG = "Manage node instance" 