TXT_SFTP_HLP_LOAD_CONFIG_FAILED = "Nepodařilo se načíst konfiguraci: {error}"
TXT_SFTP_HLP_INVALID_ADMIN_MAIL = "Neplatná e-mailová adresa administrátora."
TXT_SFTP_HLP_USER_NOT_FOUND = "Uživatel nebyl nalezen."
TXT_SFTP_HLP_INVALID_USER_MAIL = "Neplatná e-mailová adresa uživatele."
TXT_SFTP_HLP_ADMIN_MAIL_NOT_CONFIGURED = "E-mail administrátora není nastaven."
TXT_SFTP_HLP_USER_MAIL_INVALID = "E-mail nastavený uživateli '{username}' je neplatný."
TXT_SFTP_HLP_KEY_PARSE_FAILED = "Klíč se nepodařilo zpracovat: {error}"
TXT_SFTP_HLP_MAIL_SUBJECT = "Export SFTP klíče uživatele: {username}"
TXT_SFTP_HLP_MAIL_SUBJECT_PUBLIC_PRIVATE = " (veřejný + soukromý)"
TXT_SFTP_HLP_MAIL_SUBJECT_PUBLIC = " (veřejný)"
TXT_SFTP_HLP_MAIL_EXPORT_FOR = "Export SFTP klíče uživatele: {username}"
TXT_SFTP_HLP_MAIL_RECIPIENTS = "Příjemci: {recipients}"
TXT_SFTP_HLP_MAIL_PUBLIC_KEY = "Veřejný klíč:"
TXT_SFTP_HLP_MAIL_PRIVATE_KEY = "Soukromý klíč:"
TXT_SFTP_HLP_MAIL_PRIVATE_WARNING = "Přiložený archiv obsahuje soukromý klíč. Přenášejte a ukládejte jej bezpečně."
TXT_SFTP_HLP_MAIL_NO_PRIVATE_KEY = "U této položky není uložen soukromý klíč; archiv obsahuje pouze veřejný klíč."
TXT_SFTP_HLP_MAIL_ARCHIVE_ATTACHED = "Soubory klíče a návod jsou přiloženy v archivu: {filename}"
TXT_SFTP_HLP_MAIL_README_PRIVATE_LINE = "- {private_filename}: soukromý klíč; chraňte jej a nikdy jej nezveřejňujte."
TXT_SFTP_HLP_MAIL_README_NO_PRIVATE_LINE = "- U této položky není uložen soukromý klíč."
TXT_SFTP_HLP_MAIL_README_PRIVATE_NOT_AVAILABLE = "není součástí tohoto archivu"
TXT_SFTP_HLP_MAIL_README = """Balíček SFTP/SSH klíče pro uživatele: {username}

Soubory:
- {public_filename}: veřejný klíč; tento soubor lze předat správci serveru.
{private_line}

Použití:
1. Rozbalte tento ZIP archiv.
2. Ve svém SSH/SFTP klientovi importujte nebo vyberte {private_usage}.
3. V Linuxu soukromý klíč chraňte příkazem: chmod 600 <soubor-soukromého-klíče>
4. Adresa serveru a případné samostatné heslo se předávají jiným kanálem.

{generated_by}
"""
TXT_SFTP_HLP_MAIL_ZIP_FAILED = "ZIP přílohu s klíčem se nepodařilo vytvořit: {error}"
TXT_SFTP_HLP_MAIL_GENERATED_BY = "Vygenerováno pomocí SFTP Manager - SysApp v{version}."
TXT_SFTP_HLP_WITH_PRIVATE_KEY = "(se soukromým klíčem)"
TXT_SFTP_HLP_BASE64_DECODE_FAILED = "Klíč ve formátu base64 se nepodařilo dekódovat"
TXT_SFTP_HLP_INVALID_PUBLIC_FORMAT = "Neplatný formát veřejného klíče: očekáváno '<typ> <base64> [komentář]'"
TXT_SFTP_HLP_INVALID_PUBLIC_BASE64 = "Neplatný veřejný klíč: poškozená data base64"
TXT_SFTP_HLP_KEY_TYPE_MISMATCH = "Typ klíče nesouhlasí: deklarováno '{declared}', načteno '{parsed}'"
TXT_SFTP_HLP_PUBLIC_ROUNDTRIP_FAILED = "Neplatný veřejný SSH klíč: data po zpracování nesouhlasí se vstupem"
TXT_SFTP_HLP_UNSUPPORTED_KEY_TYPE = "Nepodporovaný typ veřejného SSH klíče: {key_type}"
TXT_SFTP_HLP_INVALID_PUBLIC_KEY = "Neplatný veřejný SSH klíč: {error}"
TXT_SFTP_HLP_PARAMIKO_MISSING = "Není nainstalována knihovna Paramiko: {error}"
TXT_SFTP_HLP_PRIVATE_DECODE_FAILED = "Soukromou část klíče se nepodařilo dekódovat"
TXT_SFTP_HLP_PRIVATE_ENCRYPTED = "Soukromý klíč je šifrovaný a vyžaduje heslo"
TXT_SFTP_HLP_PRIVATE_TYPE_MISMATCH = "Typ soukromého klíče nesouhlasí s veřejným klíčem"
TXT_SFTP_HLP_PRIVATE_KEY_MISMATCH = "Soukromý klíč neodpovídá zadanému veřejnému klíči"
TXT_SFTP_HLP_EXTRACT_PUBLIC_FAILED = "Ze soukromého klíče se nepodařilo získat veřejný klíč"
TXT_SFTP_HLP_INVALID_PRIVATE_KEY = "Neplatný soukromý klíč: {error}"
TXT_SFTP_HLP_KEY_ALREADY_EXISTS = "Uživatel již tento klíč má"
TXT_SFTP_HLP_KEY_GENERATE_FAILED = "Nepodařilo se vygenerovat pár SSH klíčů: {error}"
TXT_SFTP_HLP_KEY_GENERATE_EXCEPTION = "Při generování SSH klíčů nastala chyba: {error}"
TXT_SFTP_HLP_KEY_PAIR_GENERATION_FAILED = "Generování páru klíčů selhalo: {error}"
TXT_SFTP_HLP_ADD_GENERATED_KEY_FAILED = "Vygenerovaný veřejný klíč se nepodařilo přidat uživateli: {error}"
TXT_SFTP_HLP_KEY_VALIDATION_FAILED = "Validace klíče selhala: {error}"
TXT_SFTP_HLP_KEY_PROCESSING_EXCEPTION = "Při zpracování klíče nastala chyba: {error}"
TXT_SFTP_HLP_NO_CONFIG = "Nebyla předána konfigurace k aplikování."
TXT_SFTP_HLP_CONFIG_VALIDATION_FAILED = "Validace konfigurace selhala: {error}"
TXT_SFTP_HLP_SAVE_CONFIG_FAILED = "Konfiguraci se nepodařilo uložit: {error}"
TXT_SFTP_HLP_CONFIG_PATH_FAILED = "Nelze určit cestu ke vstupnímu JSON souboru: {path}"
TXT_SFTP_HLP_CIFS_MISSING = "CIFS nástroje nejsou nainstalovány. Před aplikováním SFTP mountpointů přes Sambu nainstalujte balík 'cifs-utils'."
TXT_SFTP_HLP_NO_USERS_PROCESSED = "Nebyl vytvořen ani aktualizován žádný SFTP uživatel. Příčinu najdete v logu SFTP Manageru."
TXT_SFTP_HLP_USERS_PARTIAL = "Bylo vytvořeno nebo aktualizováno pouze {created} z {expected} SFTP uživatelů."
TXT_SFTP_HLP_UNINSTALL_UNWANTED_FAILED = "Nepodařilo se odinstalovat jednoho nebo více SFTP uživatelů, kteří již nejsou v konfiguraci."
TXT_SFTP_HLP_SAMBA_TRANSACTION_FAILED = "Nepodařilo se dokončit změny Samba/CIFS mountpointů."
TXT_SFTP_HLP_SSHD_RESTART_FAILED = "Po aplikování SFTP konfigurace se nepodařilo restartovat sshd."
TXT_SFTP_HLP_APPLY_FAILED = "Konfiguraci se nepodařilo aplikovat pomocí sftpmanager.py: {error}"
TXT_SFTP_HLP_UNINSTALL_USERS_FAILED = "Uživatele se nepodařilo odinstalovat pomocí sftpmanager.py"
TXT_SFTP_HLP_UNINSTALL_USERS_EXCEPTION = "Při odinstalování SFTP uživatelů nastala chyba: {error}"
