TXT_SFTP_HLP_LOAD_CONFIG_FAILED = "Failed to load configuration: {error}"
TXT_SFTP_HLP_INVALID_ADMIN_MAIL = "Invalid admin mail address."
TXT_SFTP_HLP_USER_NOT_FOUND = "User not found."
TXT_SFTP_HLP_INVALID_USER_MAIL = "Invalid user mail address."
TXT_SFTP_HLP_ADMIN_MAIL_NOT_CONFIGURED = "Admin mail is not configured."
TXT_SFTP_HLP_USER_MAIL_INVALID = "User mail configured for '{username}' is invalid."
TXT_SFTP_HLP_KEY_PARSE_FAILED = "Failed to parse key: {error}"
TXT_SFTP_HLP_MAIL_GENERATING = "Generating the restricted SFTP key package..."
TXT_SFTP_HLP_MAIL_SUBJECT = "Restricted SFTP file-transfer access for user: {username}"
TXT_SFTP_HLP_MAIL_SUBJECT_PUBLIC_PRIVATE = " (public + private)"
TXT_SFTP_HLP_MAIL_SUBJECT_PUBLIC = " (public)"
TXT_SFTP_HLP_MAIL_EXPORT_FOR = "Restricted SFTP access for file transfer only - user: {username}"
TXT_SFTP_HLP_MAIL_ACCESS_PURPOSE = "This account is intended exclusively for SFTP file transfer. It is separate from an ordinary SSH account and does not allow an interactive shell or terminal login."
TXT_SFTP_HLP_MAIL_RECIPIENTS = "Recipients: {recipients}"
TXT_SFTP_HLP_MAIL_PUBLIC_KEY = "Public key:"
TXT_SFTP_HLP_MAIL_PRIVATE_KEY = "Private key:"
TXT_SFTP_HLP_MAIL_PRIVATE_WARNING = "The attached archive contains private key material. Transfer and store it securely."
TXT_SFTP_HLP_MAIL_NO_PRIVATE_KEY = "No private key is stored for this entry; the archive contains only the public key."
TXT_SFTP_HLP_MAIL_ARCHIVE_ATTACHED = "The key files and usage notes are attached in archive: {filename}"
TXT_SFTP_HLP_MAIL_README_PRIVATE_LINE = "- {private_filename}: private key; keep it secret and never publish it."
TXT_SFTP_HLP_MAIL_README_NO_PRIVATE_LINE = "- No private key is stored for this entry."
TXT_SFTP_HLP_MAIL_README_PRIVATE_NOT_AVAILABLE = "not included in this archive"
TXT_SFTP_HLP_MAIL_README = """Key package for restricted SFTP access for user: {username}

Access purpose:
{access_purpose}

Files:
- {public_filename}: public key; this file may be shared with the server administrator.
{private_line}

General instructions:
1. Extract this ZIP archive.
2. The server address and any non-standard port are delivered separately. The default SFTP port is 22.
3. Leave the password empty unless it was delivered separately.
4. On Linux, protect the private key with: chmod 600 <private-key-file>

Total Commander - Secure FTP/SFTP plugin:
1. Set Private key file to {private_usage} in the connection settings.
2. Set Public key file to the matching public key {public_filename}. The plugin requires both files.
3. Leave the Password field empty.

WinSCP:
1. Open Advanced -> SSH -> Authentication.
2. Select {private_usage} in Private key file; this is the file without the .pub suffix.
3. If WinSCP offers to convert the key to PuTTY/PPK format, confirm the conversion and use the converted key.
4. Leave the password field empty.
5. This account uses a server-side Samba/SFTP sandbox. File permissions are enforced by the server, so changing permissions from the client has no effect. A WinSCP warning that permissions cannot be set is expected and can be disabled in the client.

{generated_by}
"""
TXT_SFTP_HLP_MAIL_ZIP_FAILED = "Failed to create the ZIP key attachment: {error}"
TXT_SFTP_HLP_MAIL_GENERATED_BY = "Generated by SFTP Manager - SysApp v{version}."
TXT_SFTP_HLP_WITH_PRIVATE_KEY = "(with PK)"
TXT_SFTP_HLP_BASE64_DECODE_FAILED = "Failed to decode base64 key"
TXT_SFTP_HLP_INVALID_PUBLIC_FORMAT = "Invalid public key format: expected '<type> <base64> [comment]'"
TXT_SFTP_HLP_INVALID_PUBLIC_BASE64 = "Invalid public key: base64 payload is malformed"
TXT_SFTP_HLP_KEY_TYPE_MISMATCH = "Key type mismatch: declared '{declared}', parsed '{parsed}'"
TXT_SFTP_HLP_PUBLIC_ROUNDTRIP_FAILED = "Invalid SSH public key: payload does not round-trip correctly"
TXT_SFTP_HLP_UNSUPPORTED_KEY_TYPE = "Unsupported SSH public key type: {key_type}"
TXT_SFTP_HLP_INVALID_PUBLIC_KEY = "Invalid SSH public key: {error}"
TXT_SFTP_HLP_PARAMIKO_MISSING = "Paramiko is not installed: {error}"
TXT_SFTP_HLP_PRIVATE_DECODE_FAILED = "Failed to decode private key part"
TXT_SFTP_HLP_PRIVATE_ENCRYPTED = "Private key is encrypted and requires passphrase"
TXT_SFTP_HLP_PRIVATE_TYPE_MISMATCH = "Private key type does not match public key"
TXT_SFTP_HLP_PRIVATE_KEY_MISMATCH = "Private key does not match provided public key"
TXT_SFTP_HLP_EXTRACT_PUBLIC_FAILED = "Failed to extract public key from private key"
TXT_SFTP_HLP_INVALID_PRIVATE_KEY = "Invalid private key: {error}"
TXT_SFTP_HLP_KEY_ALREADY_EXISTS = "Key already exists for user"
TXT_SFTP_HLP_KEY_GENERATE_FAILED = "Failed to generate SSH key pair: {error}"
TXT_SFTP_HLP_KEY_GENERATE_EXCEPTION = "Exception during SSH key generation: {error}"
TXT_SFTP_HLP_KEY_PAIR_GENERATION_FAILED = "Key pair generation failed: {error}"
TXT_SFTP_HLP_ADD_GENERATED_KEY_FAILED = "Failed to add generated public key to user: {error}"
TXT_SFTP_HLP_KEY_VALIDATION_FAILED = "Key validation failed: {error}"
TXT_SFTP_HLP_KEY_PROCESSING_EXCEPTION = "Exception during key processing: {error}"
TXT_SFTP_HLP_NO_CONFIG = "No configuration provided to apply."
TXT_SFTP_HLP_CONFIG_VALIDATION_FAILED = "Configuration validation failed: {error}"
TXT_SFTP_HLP_SAVE_CONFIG_FAILED = "Failed to save configuration: {error}"
TXT_SFTP_HLP_CONFIG_PATH_FAILED = "Cannot determine JSON input file path: {path}"
TXT_SFTP_HLP_CIFS_MISSING = "CIFS utilities are not installed. Install package 'cifs-utils' before applying Samba-backed SFTP mountpoints."
TXT_SFTP_HLP_NO_USERS_PROCESSED = "No SFTP users were created or updated. Check the SFTP manager log for the underlying error."
TXT_SFTP_HLP_USERS_PARTIAL = "Only {created} of {expected} SFTP users were created or updated."
TXT_SFTP_HLP_UNINSTALL_UNWANTED_FAILED = "Failed to uninstall one or more SFTP users that are no longer present in the configuration."
TXT_SFTP_HLP_SAMBA_TRANSACTION_FAILED = "Failed to finalize Samba/CIFS mountpoint changes."
TXT_SFTP_HLP_SSHD_RESTART_FAILED = "Failed to restart sshd after applying SFTP configuration."
TXT_SFTP_HLP_APPLY_FAILED = "Failed to apply configuration via sftpmanager.py: {error}"
TXT_SFTP_HLP_UNINSTALL_USERS_FAILED = "Failed to uninstall users via sftpmanager.py"
TXT_SFTP_HLP_UNINSTALL_USERS_EXCEPTION = "Failed to uninstall SFTP users: {error}"
